# Generated by Django 5.0.4 on 2024-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_side', '0006_alter_address_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_no', models.IntegerField(null=True)),
            ],
        ),
    ]
