# Generated by Django 5.0.4 on 2024-06-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0053_shipping_address_alter_order_shipping_address'),
        ('user_side', '0008_shipping_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping_address',
        ),
    ]
