# Generated by Django 5.0.4 on 2024-04-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0004_rename_is_deleted_category_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
