# Generated by Django 5.0.4 on 2024-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0005_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='True', upload_to='img/'),
        ),
    ]
