# Generated by Django 5.0.4 on 2024-05-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0009_size_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
