# Generated by Django 5.0.4 on 2024-05-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0016_alter_category_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
