# Generated by Django 5.0.4 on 2024-05-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0017_product_image2_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
