# Generated by Django 5.0.4 on 2024-05-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0026_remove_cartitem_order_order_address_order_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
