# Generated by Django 5.0.4 on 2024-05-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0028_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
