# Generated by Django 5.0.4 on 2024-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0048_usercoupon_coupon_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='UserCoupon',
        ),
    ]
