# Generated by Django 5.0.4 on 2024-06-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0049_remove_coupon_users_coupon_min_order_amount_and_more'),
        ('user_side', '0007_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_side.shipping_address'),
        ),
    ]
