# Generated by Django 5.0.4 on 2024-06-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0050_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='shipping_address',
        ),
    ]
