# Generated by Django 5.0.4 on 2024-06-13 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0051_rename_address_order_shipping_address'),
        ('user_side', '0008_shipping_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_side.shipping_address'),
        ),
    ]
