# Generated by Django 5.0.4 on 2024-06-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0053_shipping_address_alter_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_side.offer'),
        ),
    ]
