# Generated by Django 5.0.4 on 2024-07-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_side', '0059_remove_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Pending', max_length=50),
        ),
    ]
